### ISSUE TITLE
Variable Input Shapes

### ISSUE THREAD

**Issue by msokoloff1** [titu1994/Keras-NASNet#10]
Would it be possible to extend the functionality beyond just static input sizes? This is useful when we are using this as a backbone to a fully convolutional model. When I create a model with spatial input dimensions as None then the model breaks during inference. because the spatial dimension of two layers being added is off by a factor of 2.

**Comment by titu1994** [comment]
For NASNet it's probably not possibly. It is very particular about it's shape requirement. However, a way to bypass this is to take floating multiples of 224x224 size. Perhaps there is also a smaller multiple of 224 which satusfies NASNet. I don't really know.
