### ISSUE TITLE
Inaccuracy in _adjust_block resp. factorized_reduction

### ISSUE THREAD

**Issue by AlfTetzlaff** [titu1994/Keras-NASNet#2]
There is an error in nasnet.py. Line 533f are just a repetition of the lines before. In the original implementation, the input to the second branch is padded and then shifted by one. This can be done like this:

p2 = ZeroPadding2D(padding=((0, 1), (0, 1)))(x)
p2 = Cropping2D(cropping=((1, 0), (1, 0)))(p2)

Which is taken from here: https://github.com/johannesu/NASNet-keras/blob/master/nasnet.py

**Comment by titu1994** [comment]
Thanks for noticing this and for the fix !
