### ISSUE TITLE
Issue when using "use_auxilary_branch=True":  The model expects 2 target arrays, but only received one array. Found: array with shape (600, 2)

### ISSUE THREAD

**Issue by Rabia-Metis** [titu1994/Keras-NASNet#5]
![image](https://user-images.githubusercontent.com/29912627/33656809-107307ea-da99-11e7-8f27-e363c7037e10.png)
Kindly help me sort it out. I am using the model with the following parameters:
model = NASNet(classes=2,input_shape=(224, 224, 3), weights=None, penultimate_filters=4032,
                  nb_blocks=6,use_auxilary_branch=True, skip_reduction=False)

**Comment by titu1994** [comment]
Since you are using the auxiliary branch, you need to duplicate your labels to train models.

So the input data has to be (X_train, [y_train, y_train]) and the validation / test data needs to be [X_test, [y_test, y_test])
