### ISSUE TITLE
Pooling kernel size

### ISSUE THREAD

**Issue by uhfband** [titu1994/Keras-NASNet#6]
Сould you please clarify, It's ok to have pool size less than stride size?
eg nasnet.py line 620
p1 = AveragePooling2D((1, 1), strides=(2, 2), padding='valid', name='adjust_avg_pool_1_%s' % id)(p)

**Comment by titu1994** [comment]
Yes. It's a point wise averaging which simply reduces the spacial dimension by half. 

Since the weights load correctly, and predictions are correct, such an operation is correct.
