### ISSUE TITLE
Unable to open object (object 'global_average_pooling2d_1' doesn't exist)

### ISSUE THREAD

**Issue by OleksandrPopovych** [titu1994/Keras-NASNet#7]
Hi, there. I encountered a problem: KeyError: "Unable to open object (object 'global_average_pooling2d_1' doesn't exist)". 
Here my code snippet:
```
model_name = "nasnet_large_500_300"

net_model = NASNetLarge(input_shape=input_shape, weights='imagenet', include_top=False, pooling='avg')
# append classification layer
x = net_model.output
final_output = Dense(nb_classes, activation='sigmoid', name='fc11')(x)

model = Model(inputs=net_model.input, outputs=final_output)
```
Could someone help me with this? 
UPD: As I found keras couldn't load weights from h5 file

**Comment by titu1994** [comment]
Turns out I made an error when saving the weights for the "No Top" models. I have updated new weights, which should work. However, you will need to delete the local copy stored at ~/.keras/models/NASNet***.h5

**Comment by ivo-leonov** [comment]
Hey, thanks a lot!
I was having the same issue and was trying to remove the top myself, but it didn't work. For the sake of curiosity, could you please explain how you removed the top?
I tried the following:
* load weights with top
* remove the last three layers on top using pop():

```python
for i in range(0, 3):
    base_model.layers.pop()
    base_model.outputs = [base_model.layers[-1].output]
    base_model.layers[-1].outbound_nodes = []
```
But it didn't work when I attached a new avg-pool and a softmax.

**Comment by titu1994** [comment]
It wasn't actually an error with the model itself, but the weight file. When I was creating the no top models, I deleted the extra layers manually, but forgot to update the layer_names property in the weight file. 

So even though the weight files didnt contain those weights anymore, it attempted to load them causing the error. 

I fixed them by saving the weights properly this time.

**Comment by titu1994** [comment]
To remove the top, I simply don't add the extra classification layers when building the model. For Models in Keras, you can't apply pop operations.

**Comment by ivo-leonov** [comment]
Okay, so how do I edit a weight file to remove the top from the weights? It would be awesome if you could explain that. Thanks!
